version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: fb_ads_bot_postgres
    environment:
      POSTGRES_DB: fb_ads_bot_prod
      POSTGRES_USER: fb_ads_user
      POSTGRES_PASSWORD: secure_password_123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fb_ads_user -d fb_ads_bot_prod"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Telegram Bot Application
  bot:
    build: .
    container_name: fb_ads_bot_app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - ENVIRONMENT=production
    env_file:
      - .env.prod
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    ports:
      - "8000:8000"
      - "8080:8080"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  postgres_data:
    driver: local 