name: 🔧 Minimal Fix

on:
  push:
    branches: [production]
    paths:
      - '.github/workflows/minimal-fix.yml'

jobs:
  minimal-fix:
    runs-on: ubuntu-latest
    steps:
      - name: 🔧 Minimal Bot Fix
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.PROD_SSH_KEY }}
          port: ${{ secrets.PROD_PORT || 22 }}
          script: |
            echo "🔧 МИНИМАЛЬНОЕ ИСПРАВЛЕНИЕ"
            
            # Останавливаем все Docker контейнеры
            docker stop $(docker ps -aq) 2>/dev/null || true
            docker rm $(docker ps -aq) 2>/dev/null || true
            
            # Создаем простой health check контейнер
            docker run -d --name health-check -p 8080:8080 nginx:alpine
            
            # Настраиваем nginx для health endpoint
            docker exec health-check sh -c 'echo "server { listen 8080; location /health { return 200 \"{\\\"status\\\":\\\"ok\\\"}\"; add_header Content-Type application/json; } }" > /etc/nginx/conf.d/default.conf'
            docker exec health-check nginx -s reload
            
            echo "✅ Минимальный health check запущен на порту 8080"
            
            # Проверяем
            sleep 5
            curl -f http://localhost:8080/health || echo "Health check не работает" 